apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-tiltak
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tiltakspenger-tiltak.intern.nav.no
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  liveness:
    path: /isalive
    initialDelay: 15
  readiness:
    path: /isready
    initialDelay: 15
    periodSeconds: 5
    failureThreshold: 1
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 2000Mi
    requests:
      memory: 1000Mi
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - name: tiltakspenger-tiltak
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        cascadingDelete: true
        databases:
          - name: tiltak
            envVarPrefix: DB
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad-api
        - application: tiltakspenger-saksbehandling-api
    outbound:
      rules:
        - application: tiltakshistorikk
          namespace: team-mulighetsrommet
        - application: logging
          namespace: nais-system
      external:
        - host: tiltakspenger-arena.prod-fss-pub.nais.io
  env:
    - name: ARENA_URL
      value: https://tiltakspenger-arena.prod-fss-pub.nais.io
    - name: ARENA_SCOPE
      value: api://prod-fss.tpts.tiltakspenger-arena/.default
    - name: TILTAKSHISTORIKK_SCOPE
      value: api://prod-gcp.team-mulighetsrommet.tiltakshistorikk/.default
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
