package no.nav.tiltakspenger.tiltak.clients.tiltakshistorikk.dto

import no.nav.tiltakspenger.libs.tiltak.TiltakResponsDTO

enum class TiltakskodeDto {
    ARBEIDSFORBEREDENDE_TRENING,
    ARBEIDSRETTET_REHABILITERING,
    AVKLARING,
    DIGITALT_OPPFOLGINGSTILTAK,
    ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING,
    ENKELTPLASS_FAG_OG_YRKESOPPLAERING,
    GRUPPE_ARBEIDSMARKEDSOPPLAERING,
    GRUPPE_FAG_OG_YRKESOPPLAERING,
    HOYERE_UTDANNING,
    JOBBKLUBB,
    OPPFOLGING,
    VARIG_TILRETTELAGT_ARBEID_SKJERMET,

    ARBEIDSMARKEDSOPPLAERING,
    NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV,
    STUDIESPESIALISERING,
    FAG_OG_YRKESOPPLAERING,
    HOYERE_YRKESFAGLIG_UTDANNING,
}

fun TiltakskodeDto.toArenaKode(): TiltakResponsDTO.TiltakTypeDTO {
    return when (this) {
        TiltakskodeDto.ARBEIDSFORBEREDENDE_TRENING -> TiltakResponsDTO.TiltakTypeDTO.ARBFORB
        TiltakskodeDto.ARBEIDSRETTET_REHABILITERING -> TiltakResponsDTO.TiltakTypeDTO.ARBRRHDAG
        TiltakskodeDto.AVKLARING -> TiltakResponsDTO.TiltakTypeDTO.AVKLARAG
        TiltakskodeDto.DIGITALT_OPPFOLGINGSTILTAK -> TiltakResponsDTO.TiltakTypeDTO.DIGIOPPARB
        TiltakskodeDto.GRUPPE_ARBEIDSMARKEDSOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.GRUPPEAMO
        TiltakskodeDto.ARBEIDSMARKEDSOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.ARBEIDSMARKEDSOPPLAERING
        TiltakskodeDto.NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV -> TiltakResponsDTO.TiltakTypeDTO.NORSKOPPLAERING_GRUNNLEGGENDE_FERDIGHETER_FOV
        TiltakskodeDto.STUDIESPESIALISERING -> TiltakResponsDTO.TiltakTypeDTO.STUDIESPESIALISERING
        TiltakskodeDto.GRUPPE_FAG_OG_YRKESOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.GRUFAGYRKE
        TiltakskodeDto.FAG_OG_YRKESOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.FAG_OG_YRKESOPPLAERING
        TiltakskodeDto.HOYERE_YRKESFAGLIG_UTDANNING -> TiltakResponsDTO.TiltakTypeDTO.HOYERE_YRKESFAGLIG_UTDANNING
        TiltakskodeDto.JOBBKLUBB -> TiltakResponsDTO.TiltakTypeDTO.JOBBK
        TiltakskodeDto.OPPFOLGING -> TiltakResponsDTO.TiltakTypeDTO.INDOPPFAG
        TiltakskodeDto.VARIG_TILRETTELAGT_ARBEID_SKJERMET -> TiltakResponsDTO.TiltakTypeDTO.VASV
        TiltakskodeDto.ENKELTPLASS_ARBEIDSMARKEDSOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.ENKELAMO
        TiltakskodeDto.ENKELTPLASS_FAG_OG_YRKESOPPLAERING -> TiltakResponsDTO.TiltakTypeDTO.ENKFAGYRKE
        TiltakskodeDto.HOYERE_UTDANNING -> TiltakResponsDTO.TiltakTypeDTO.HOYEREUTD
    }
}
