name: Deploy to NAIS

on:
  workflow_call:
    inputs:
      NAIS_ENV:
        required: true
        type: string
      IMAGE:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to NAIS (${{ inputs.NAIS_ENV }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.NAIS_ENV }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy to NAIS
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: ${{ inputs.NAIS_ENV }}-gcp
          RESOURCE: .nais/nais-${{ inputs.NAIS_ENV }}.yml
          VAR: image=${{ inputs.IMAGE }}
