name: Test and build

on:
  workflow_call:
    inputs:
      buildImage:
        required: false
        type: boolean
        default: true
    outputs:
      IMAGE:
        description: "Docker image"
        value: ${{ jobs.build.outputs.IMAGE }}
    secrets:
      SLACK_VARSEL_WEBHOOK_URL:
        required: true

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      IMAGE: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Ikke la tokenet ligge igjen i .git/config - test-/byggsteget kjører avhengigheters kode.
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Test and build application
        run: ./gradlew build --info installDist --configuration-cache

      - name: Build and push docker image
        # Versjonsoversikt (tag -> SHA): https://github.com/nais/docker-build-push/tags
        # Denne SHA-en: https://github.com/nais/docker-build-push/commit/31c3a7321909bcb20799fdf46153fec721fd9512
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-push
        if: inputs.buildImage == true
        with:
          team: tpts

      - name: Notify Slack in case of build failure
        if: failure() && github.ref == 'refs/heads/main'
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[${{ github.event.repository.name }}] Build failed :cry:\", \"color\": \"danger\", \"fields\": [ { \"title\": \"Author\", \"value\": \"$AUTHOR\", \"short\": false }, { \"title\": \"Commit\", \"value\": \"<https://github.com/${{ github.repository }}/commit/$GITHUB_SHA|$GITHUB_SHA>\", \"short\": false } ] }] }" "$WEBHOOK_URL"
        env:
          BRANCH: ${{ github.ref }}
          AUTHOR: ${{ github.event.pusher.name }}
          WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
