name: Test and build

on:
  workflow_call:
    inputs:
      buildImage:
        required: false
        type: boolean
        default: true
    outputs:
      IMAGE:
        description: "Docker image"
        value: ${{ jobs.build.outputs.IMAGE }}
    secrets:
      SLACK_VARSEL_WEBHOOK_URL:
        required: true

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      IMAGE: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test and build application
        run: ./gradlew build --info installDist

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        if: inputs.buildImage == true
        with:
          team: tpts

      - name: Notify Slack in case of build failure
        if: failure() && github.ref == 'refs/heads/main'
        run: |
          curl -X POST --data-urlencode "payload={ \"attachments\": [{ \"pretext\": \"[${{ github.event.repository.name }}] Build failed :cry:\", \"color\": \"danger\", \"fields\": [ { \"title\": \"Author\", \"value\": \"$AUTHOR\", \"short\": false }, { \"title\": \"Commit\", \"value\": \"<https://github.com/${{ github.repository }}/commit/$GITHUB_SHA|$GITHUB_SHA>\", \"short\": false } ] }] }" $WEBHOOK_URL
        env:
          BRANCH: ${{ github.ref }}
          AUTHOR: ${{ github.event.pusher.name }}
          WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
