name: Build, push and deploy to prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Test and build
    uses: ./.github/workflows/.test-and-build.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}

  deploy-dev:
    name: Deploy to NAIS (dev)
    needs: build
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}

  deploy-prod:
    name: Deploy to NAIS (prod)
    needs: build
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: prod
      IMAGE: ${{ needs.build.outputs.IMAGE }}
