name: Test/build on feature branch push

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Test and build
    uses: ./.github/workflows/.test-and-build.yml
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      id-token: write
    with:
      buildImage: false
    secrets:
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}